server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gosaintmrc/spring-cloud-config      # git仓库地址
          search-paths: /**                                           # 配置文件所在的目录
          username: gosaintmrc@aliyun.com                        # git用户名和密码
          password:           # 由于公共仓库可以不用用户名和密码，可以不用设置
      label: master                 # 分支

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
